"""
Модуль для работы с базой данных
"""

from sqlalchemy import create_engine, Column, String, DateTime, Integer, Float, Text, or_
from sqlalchemy.orm import declarative_base, sessionmaker, Session
from datetime import datetime, timezone
from typing import List, Optional
import json
import uuid

from config import settings

# Создаём движок БД
engine = create_engine(
    settings.database_url,
    connect_args={"check_same_thread": False}  # Для SQLite
)

# Создаём фабрику сессий
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Базовый класс для моделей
Base = declarative_base()


# ============================================
# МОДЕЛИ БД
# ============================================

class PipelineRun(Base):
    """Модель запуска pipeline"""
    __tablename__ = "pipeline_runs"
    
    run_id = Column(String, primary_key=True, index=True)
    input_path = Column(String, nullable=False)
    output_path = Column(String, nullable=False)
    status = Column(String, nullable=False, default="pending")
    
    # Прогресс
    current_stage = Column(Integer, nullable=True)
    overall_progress = Column(Float, default=0.0)
    
    # Качество
    quality_score = Column(Float, nullable=True)
    quality_category = Column(String, nullable=True)
    
    # Временные метки
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    
    # Ошибки
    error_message = Column(Text, nullable=True)
    
    # Путь к конфигу
    config_path = Column(String, nullable=True)

    # Тип поражения (glioblastoma / multiple_sclerosis)
    lesion_type = Column(String, nullable=True, default='glioblastoma')

    # The Kappa dataset this run numbers its subjects in and uploads to. Fixed
    # once at start (backend/numbering.py) so numbering and upload cannot
    # target different datasets. NULL for CLI runs and runs with no Kappa
    # session, and for runs started before this column existed.
    kappa_dataset_id = Column(Integer, nullable=True)

    # Остановка оператором: на каком этапе прервали и кто нажал кнопку.
    stopped_at_stage = Column(Integer, nullable=True)
    stopped_by = Column(String, nullable=True)

    # Если этот запуск — requeue (повторная обработка после ручной правки),
    # здесь лежит run_id исходного запуска. NULL для обычных запусков.
    parent_run_id = Column(String, nullable=True)

    # Deferred Kappa delivery. `kappa_upload_status` is NULL for runs that
    # never intended to upload (CLI, no Kappa session) — the worker ignores
    # those entirely. `kappa_upload_detail` is a JSON blob (see
    # backend/kappa_delivery.py). `kappa_user_id` is the Kappa account that
    # started the run: session ids rotate on re-login, user ids do not, so
    # this is what finds a live token days later.
    kappa_upload_status = Column(String, nullable=True)
    kappa_upload_next_attempt = Column(DateTime, nullable=True)
    kappa_upload_detail = Column(Text, nullable=True)
    kappa_user_id = Column(Integer, nullable=True)

    # Sessions this run rebuilt because the doctor corrected their modality
    # set. JSON list of "sub-NNN_ses-NNN". Their results in Kappa were
    # computed from a set now known to be wrong, so they supersede rather
    # than duplicate — see kappa_uploader.
    reprocessed_sessions = Column(Text, nullable=True)


class StageExecution(Base):
    """Модель выполнения отдельного этапа"""
    __tablename__ = "stage_executions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String, nullable=False, index=True)
    stage_number = Column(Integer, nullable=False)
    stage_name = Column(String, nullable=False)
    status = Column(String, nullable=False, default="pending")
    progress = Column(Float, default=0.0)
    
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    
    error_message = Column(Text, nullable=True)


# ============================================
# CRUD ОПЕРАЦИИ
# ============================================

def get_db() -> Session:
    """Получить сессию БД"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_pipeline_run(
    db: Session,
    input_path: str,
    output_path: str,
    lesion_type: str = 'glioblastoma',
    parent_run_id: Optional[str] = None,
    kappa_dataset_id: Optional[int] = None,
    run_id: Optional[str] = None,
    kappa_upload_status: Optional[str] = None,
    kappa_user_id: Optional[int] = None,
    reprocessed_sessions: Optional[str] = None,
) -> PipelineRun:
    """Создать новый запуск pipeline.

    run_id may be pre-generated by the caller — needed when the BIDS
    numbering scope has to be decided (backend/numbering.py) before the row
    exists, since a pending scope (Kappa unreachable at start) is keyed by
    this exact run_id and must match what get_pipeline_run() later returns.

    kappa_upload_status is the delivery intent, recorded at birth: 'pending'
    when the caller supplied a live Kappa session, None (the default) for
    CLI/orchestrator runs that never intended to upload. A None status keeps
    the run out of the deferred-delivery worker's queue permanently.
    """
    run_id = run_id or str(uuid.uuid4())

    run = PipelineRun(
        run_id=run_id,
        input_path=input_path,
        output_path=output_path,
        status="pending",
        created_at=datetime.now(timezone.utc),
        lesion_type=lesion_type,
        parent_run_id=parent_run_id,
        kappa_dataset_id=kappa_dataset_id,
        kappa_upload_status=kappa_upload_status,
        kappa_user_id=kappa_user_id,
        reprocessed_sessions=reprocessed_sessions,
    )
    
    db.add(run)
    db.commit()
    db.refresh(run)
    
    # Создаём записи для всех этапов
    stage_names = settings.stage_names_ru
    for stage_num in range(1, 8):
        stage = StageExecution(
            run_id=run_id,
            stage_number=stage_num,
            stage_name=stage_names[stage_num],
            status="pending"
        )
        db.add(stage)
    
    db.commit()
    
    return run


def get_pipeline_run(db: Session, run_id: str) -> Optional[PipelineRun]:
    """Получить информацию о запуске по ID"""
    return db.query(PipelineRun).filter(PipelineRun.run_id == run_id).first()


def get_active_run_by_output_path(db: Session, output_path: str) -> Optional[PipelineRun]:
    """Найти запуск в статусе pending/running на заданном output_path.

    Несколько разных run_id (например, run и его собственный requeue-потомок)
    могут указывать на один и тот же output_path. Перед тем как поставить в
    очередь ещё один запуск на этот путь, нужно убедиться, что там прямо
    сейчас не работает другой процесс — иначе два orchestrator-процесса
    начнут конкурентно писать в один bids_organized/dataset_mapping.json.
    """
    return db.query(PipelineRun).filter(
        PipelineRun.output_path == output_path,
        PipelineRun.status.in_(["running", "pending"])
    ).first()


def update_pipeline_run(
    db: Session,
    run_id: str,
    **kwargs
) -> Optional[PipelineRun]:
    """Обновить информацию о запуске"""
    run = get_pipeline_run(db, run_id)
    if not run:
        return None
    
    for key, value in kwargs.items():
        if hasattr(run, key):
            setattr(run, key, value)
    
    db.commit()
    db.refresh(run)
    return run


def update_pipeline_run_if_active(
    db: Session,
    run_id: str,
    **kwargs
) -> Optional[PipelineRun]:
    """
    Apply updates only while the run is still pending or running.

    Atomic at the SQL level so a late completed/failed write cannot
    overwrite a stop that already committed on another Session.
    Returns None when the row was already terminal (or missing).
    """
    allowed = {k: v for k, v in kwargs.items() if hasattr(PipelineRun, k)}
    if not allowed:
        return get_pipeline_run(db, run_id)

    rows = (
        db.query(PipelineRun)
        .filter(
            PipelineRun.run_id == run_id,
            PipelineRun.status.in_(["pending", "running"]),
        )
        .update(allowed, synchronize_session="fetch")
    )
    db.commit()
    if rows == 0:
        return None
    return get_pipeline_run(db, run_id)


def reconcile_orphaned_runs(db: Session) -> int:
    """Mark runs stuck in a non-terminal state as failed at startup.

    A pipeline run executes as a subprocess of the backend, so it cannot outlive
    a backend/container restart. Any run still marked 'running' or 'pending' when
    the backend boots is therefore orphaned — its process died. Left untouched,
    these 'running' rows keep the frontend history auto-refresh polling forever
    and mislead the user into thinking work is still in progress.

    Returns the number of runs reconciled.
    """
    orphaned = db.query(PipelineRun).filter(
        PipelineRun.status.in_(["running", "pending"])
    ).all()
    if not orphaned:
        return 0

    now = datetime.utcnow()
    for run in orphaned:
        run.status = "failed"
        run.completed_at = now
        run.error_message = (
            run.error_message
            or "Прогон прерван перезапуском сервиса (orphaned at startup)"
        )
        # A failed run produced nothing to upload. Left 'pending' it would
        # haunt the summary banner forever, because the delivery worker only
        # ever looks at completed runs.
        run.kappa_upload_status = None
        run.kappa_upload_next_attempt = None
    db.commit()
    return len(orphaned)


def get_stage_executions(db: Session, run_id: str) -> List[StageExecution]:
    """Получить все этапы для запуска"""
    return db.query(StageExecution).filter(
        StageExecution.run_id == run_id
    ).order_by(StageExecution.stage_number).all()


def update_stage_execution(
    db: Session,
    run_id: str,
    stage_number: int,
    **kwargs
) -> Optional[StageExecution]:
    """Обновить информацию об этапе"""
    stage = db.query(StageExecution).filter(
        StageExecution.run_id == run_id,
        StageExecution.stage_number == stage_number
    ).first()
    
    if not stage:
        return None
    
    for key, value in kwargs.items():
        if hasattr(stage, key):
            setattr(stage, key, value)
    
    db.commit()
    db.refresh(stage)
    return stage


def get_pipeline_history(
    db: Session,
    limit: int = 50,
    offset: int = 0
) -> tuple[List[PipelineRun], int]:
    """Получить историю запусков с пагинацией"""
    query = db.query(PipelineRun).order_by(PipelineRun.created_at.desc())
    
    total = query.count()
    runs = query.limit(limit).offset(offset).all()
    
    return runs, total


# ============================================
# ИНИЦИАЛИЗАЦИЯ БД
# ============================================

def init_db():
    """Инициализировать базу данных и применить миграции колонок."""
    Base.metadata.create_all(bind=engine)
    _migrate_add_lesion_type()
    _migrate_add_parent_run_id()
    _migrate_add_stop_columns()
    _migrate_add_kappa_dataset_id()
    _migrate_add_kappa_delivery()
    _migrate_add_reprocessed_sessions()


def _migrate_add_lesion_type():
    """Add lesion_type column to pipeline_runs if it doesn't exist yet."""
    with engine.connect() as conn:
        cols = [row[1] for row in conn.execute(
            __import__('sqlalchemy').text("PRAGMA table_info(pipeline_runs)")
        )]
        if 'lesion_type' not in cols:
            conn.execute(__import__('sqlalchemy').text(
                "ALTER TABLE pipeline_runs ADD COLUMN lesion_type TEXT DEFAULT 'glioblastoma'"
            ))
            conn.commit()


def _migrate_add_parent_run_id():
    """Add parent_run_id column to pipeline_runs if it doesn't exist yet."""
    with engine.connect() as conn:
        cols = [row[1] for row in conn.execute(
            __import__('sqlalchemy').text("PRAGMA table_info(pipeline_runs)")
        )]
        if 'parent_run_id' not in cols:
            conn.execute(__import__('sqlalchemy').text(
                "ALTER TABLE pipeline_runs ADD COLUMN parent_run_id VARCHAR"
            ))
            conn.commit()


def _migrate_add_stop_columns():
    """Add stopped_at_stage / stopped_by to pipeline_runs if not present."""
    with engine.connect() as conn:
        cols = [row[1] for row in conn.execute(
            __import__('sqlalchemy').text("PRAGMA table_info(pipeline_runs)")
        )]
        if 'stopped_at_stage' not in cols:
            conn.execute(__import__('sqlalchemy').text(
                "ALTER TABLE pipeline_runs ADD COLUMN stopped_at_stage INTEGER"
            ))
        if 'stopped_by' not in cols:
            conn.execute(__import__('sqlalchemy').text(
                "ALTER TABLE pipeline_runs ADD COLUMN stopped_by VARCHAR"
            ))
        conn.commit()


def _migrate_add_kappa_dataset_id():
    """Add kappa_dataset_id to pipeline_runs if it doesn't exist yet."""
    with engine.connect() as conn:
        cols = [row[1] for row in conn.execute(
            __import__('sqlalchemy').text("PRAGMA table_info(pipeline_runs)")
        )]
        if 'kappa_dataset_id' not in cols:
            conn.execute(__import__('sqlalchemy').text(
                "ALTER TABLE pipeline_runs ADD COLUMN kappa_dataset_id INTEGER"
            ))
            conn.commit()


def _migrate_add_reprocessed_sessions():
    """Add pipeline_runs.reprocessed_sessions if it is not there yet."""
    import sqlalchemy
    with engine.connect() as conn:
        cols = [row[1] for row in conn.execute(
            sqlalchemy.text("PRAGMA table_info(pipeline_runs)")
        )]
        if 'reprocessed_sessions' not in cols:
            conn.execute(sqlalchemy.text(
                "ALTER TABLE pipeline_runs ADD COLUMN reprocessed_sessions TEXT"
            ))
            conn.commit()


def _migrate_add_kappa_delivery():
    """Add the deferred-delivery columns to pipeline_runs, and mark recent
    completed runs as owing delivery so they are picked up once.

    The backfill window is deliberately bounded: without it the migration
    would revive every run ever completed, including ones nobody intended to
    upload. Rows it marks have no kappa_user_id — the worker falls back to
    owner_of_dataset(kappa_dataset_id), which works precisely because the
    WHERE clause requires that column to be set.
    """
    import sqlalchemy
    with engine.connect() as conn:
        cols = [row[1] for row in conn.execute(
            sqlalchemy.text("PRAGMA table_info(pipeline_runs)")
        )]
        added = False
        for name, ddl in [
            ("kappa_upload_status", "kappa_upload_status VARCHAR"),
            ("kappa_upload_next_attempt", "kappa_upload_next_attempt DATETIME"),
            ("kappa_upload_detail", "kappa_upload_detail TEXT"),
            ("kappa_user_id", "kappa_user_id INTEGER"),
        ]:
            if name not in cols:
                conn.execute(sqlalchemy.text(
                    f"ALTER TABLE pipeline_runs ADD COLUMN {ddl}"
                ))
                added = True
        if added:
            conn.execute(sqlalchemy.text(
                "UPDATE pipeline_runs SET kappa_upload_status = 'pending' "
                " WHERE status = 'completed' "
                "   AND kappa_upload_status IS NULL "
                "   AND kappa_dataset_id IS NOT NULL "
                "   AND completed_at >= datetime('now', '-30 days')"
            ))
        conn.commit()


def reset_db():
    """Удалить и пересоздать все таблицы (для разработки)"""
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

def _naive_utc(dt: Optional[datetime]) -> Optional[datetime]:
    """SQLite stores no timezone. Strip it on the way in so that comparisons
    inside the database are between like and like."""
    if dt is None:
        return None
    return dt.astimezone(timezone.utc).replace(tzinfo=None) if dt.tzinfo else dt


def set_kappa_delivery(
    db: Session,
    run_id: str,
    status: Optional[str],
    next_attempt: Optional[datetime],
    detail: dict,
) -> None:
    """Persist the verdict of one delivery attempt."""
    run = get_pipeline_run(db, run_id)
    if run is None:
        return
    run.kappa_upload_status = status
    run.kappa_upload_next_attempt = _naive_utc(next_attempt)
    run.kappa_upload_detail = json.dumps(detail, ensure_ascii=False)
    db.commit()


def get_kappa_delivery(run: PipelineRun) -> dict:
    """The detail blob, or {} when unset or unparseable. Never raises: a
    corrupt blob must not take down the history page."""
    raw = getattr(run, "kappa_upload_detail", None)
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except (ValueError, TypeError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def runs_due_for_delivery(
    db: Session, now: datetime, limit: int = 5
) -> List[PipelineRun]:
    """Completed runs that still owe data and whose next attempt is due."""
    return (
        db.query(PipelineRun)
        .filter(
            PipelineRun.status == "completed",
            PipelineRun.kappa_upload_status == "pending",
            or_(
                PipelineRun.kappa_upload_next_attempt.is_(None),
                PipelineRun.kappa_upload_next_attempt <= _naive_utc(now),
            ),
        )
        .order_by(PipelineRun.completed_at.asc())
        .limit(limit)
        .all()
    )


def superseding_sessions(run) -> set:
    """Session keys whose Kappa contents this run supersedes. Never raises:
    a corrupt value must not stop an upload."""
    raw = getattr(run, "reprocessed_sessions", None)
    if not raw:
        return set()
    try:
        parsed = json.loads(raw)
    except (ValueError, TypeError):
        return set()
    return {str(x) for x in parsed} if isinstance(parsed, list) else set()
