datasets:
  26:glioblastoma:current: 249
  26:glioblastoma:3a183dc7: 249
  26:multiple_sclerosis:current: 158
  26:multiple_sclerosis:1e2b93ad: 158
lesion_types:
- id: glioblastoma
  name: Глиобластома
  name_en: Glioblastoma
- id: multiple_sclerosis
  name: Рассеянный склероз
  name_en: Multiple Sclerosis
